/* GENERATED — do not edit this file.
 *
 * The shared half of the world (camera maths, the owner's plan, the seating rule, the furniture
 * paths) lives once, in apps/web/src/world/*.ts, and is bundled here so the design prototype can
 * use the very same code instead of a copy.
 *
 * Rebuild:  node scripts/build-world-lib.mjs
 * Verify:   node scripts/build-world-lib.mjs --check     (the gate runs this)
 */
"use strict";
var WORLD_LIB = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // apps/web/src/world/demo-entry.ts
  var demo_entry_exports = {};
  __export(demo_entry_exports, {
    DEFAULT_LAYOUT: () => DEFAULT_LAYOUT,
    DOUBLE_CLICK_FACTOR: () => DOUBLE_CLICK_FACTOR,
    EASE: () => EASE,
    GLIDE_FRICTION: () => GLIDE_FRICTION,
    GLIDE_STOP: () => GLIDE_STOP,
    LADDER: () => LADDER,
    MAX_SCALE: () => MAX_SCALE,
    MIN_SCALE: () => MIN_SCALE,
    PROP_GRID: () => PROP_GRID,
    PROP_PATHS: () => PROP_PATHS,
    SPRITES: () => SPRITES,
    WORLD: () => WORLD,
    cameraTransform: () => cameraTransform,
    centreOn: () => centreOn,
    clampCamera: () => clampCamera,
    clampCameraForZoom: () => clampCameraForZoom,
    clampScale: () => clampScale,
    defaultPlan: () => defaultPlan,
    desksOf: () => desksOf,
    distanceBetween: () => distanceBetween,
    doubleClickZoom: () => doubleClickZoom,
    ease: () => ease,
    fitCamera: () => fitCamera,
    glideDistance: () => glideDistance,
    glideStep: () => glideStep,
    midpoint: () => midpoint,
    nextRung: () => nextRung,
    panBy: () => panBy,
    pinchCamera: () => pinchCamera,
    roomAt: () => roomAt,
    seatAgents: () => seatAgents,
    shapeFor: () => shapeFor,
    snap: () => snap,
    sprite: () => sprite,
    toPlan: () => toPlan,
    toScreen: () => toScreen,
    wheelFactor: () => wheelFactor,
    zoomAbout: () => zoomAbout,
    zoomBy: () => zoomBy,
    zoomByCentre: () => zoomByCentre
  });

  // apps/web/src/world/layout.data.ts
  var WORLD = { w: 1920, h: 1200, snap: 16, grain: 2 };
  var ROOMS = [
    {
      "id": "exec",
      "key": "exec",
      "name": "Executive Wing",
      "sub": "Leadership & Strategy",
      "theme": "executive-suite",
      "x": 80,
      "y": 80,
      "w": 460,
      "h": 360
    },
    {
      "id": "eng",
      "key": "eng",
      "name": "AI Core & Engineering Lab",
      "sub": "Models \xB7 Systems \xB7 Infrastructure",
      "theme": "engineering-lab",
      "x": 580,
      "y": 80,
      "w": 680,
      "h": 420
    },
    {
      "id": "board",
      "key": "board",
      "name": "Boardroom",
      "sub": "",
      "theme": "boardroom-hub",
      "x": 580,
      "y": 520,
      "w": 320,
      "h": 440
    },
    {
      "id": "design",
      "key": "design",
      "name": "Design & Product Atelier",
      "sub": "UI/UX \xB7 Assets \xB7 Prototypes",
      "theme": "design-studio",
      "x": 80,
      "y": 480,
      "w": 460,
      "h": 480
    },
    {
      "id": "ops",
      "key": "ops",
      "name": "Operations & Growth",
      "sub": "",
      "theme": "operations-hub",
      "x": 930,
      "y": 520,
      "w": 330,
      "h": 440
    },
    {
      "id": "lounge",
      "key": "lounge",
      "name": "Breakroom & Lounge",
      "sub": "Recharge \xB7 Arcade \xB7 Social",
      "theme": "lounge-area",
      "x": 1300,
      "y": 80,
      "w": 380,
      "h": 880
    }
  ];
  var DESKS = [
    {
      "id": "d0",
      "dept": "Executive",
      "x": 260,
      "y": 180,
      "deskType": "sp-desk-straight",
      "w": 84,
      "h": 84
    },
    {
      "id": "d1",
      "dept": "Executive",
      "x": 380,
      "y": 180,
      "deskType": "sp-desk-straight",
      "w": 84,
      "h": 84
    },
    {
      "id": "d2",
      "dept": "Engineering",
      "x": 620,
      "y": 220,
      "deskType": "sp-desk-modesty-panel",
      "w": 84,
      "h": 84
    },
    {
      "id": "d3",
      "dept": "Engineering",
      "x": 780,
      "y": 220,
      "deskType": "sp-desk-modesty-panel",
      "w": 84,
      "h": 84
    },
    {
      "id": "d4",
      "dept": "Engineering",
      "x": 940,
      "y": 220,
      "deskType": "sp-desk-modesty-panel",
      "w": 84,
      "h": 84
    },
    {
      "id": "d5",
      "dept": "Engineering",
      "x": 620,
      "y": 350,
      "deskType": "sp-desk-modesty-panel",
      "w": 84,
      "h": 84
    },
    {
      "id": "d6",
      "dept": "Engineering",
      "x": 780,
      "y": 350,
      "deskType": "sp-desk-modesty-panel",
      "w": 84,
      "h": 84
    },
    {
      "id": "d7",
      "dept": "Engineering",
      "x": 940,
      "y": 350,
      "deskType": "sp-desk-modesty-panel",
      "w": 84,
      "h": 84
    },
    {
      "id": "d8",
      "dept": "Design",
      "x": 240,
      "y": 560,
      "deskType": "sp-desk-modesty-panel",
      "w": 84,
      "h": 84
    },
    {
      "id": "d9",
      "dept": "Design",
      "x": 380,
      "y": 560,
      "deskType": "sp-desk-modesty-panel",
      "w": 84,
      "h": 84
    },
    {
      "id": "d10",
      "dept": "Design",
      "x": 240,
      "y": 690,
      "deskType": "sp-desk-modesty-panel",
      "w": 84,
      "h": 84
    },
    {
      "id": "d11",
      "dept": "Design",
      "x": 380,
      "y": 690,
      "deskType": "sp-desk-modesty-panel",
      "w": 84,
      "h": 84
    },
    {
      "id": "d12",
      "dept": "Operations",
      "x": 970,
      "y": 680,
      "deskType": "sp-desk-straight",
      "w": 84,
      "h": 84
    },
    {
      "id": "d13",
      "dept": "Operations",
      "x": 1110,
      "y": 680,
      "deskType": "sp-desk-straight",
      "w": 84,
      "h": 84
    },
    {
      "id": "d14",
      "dept": "Operations",
      "x": 970,
      "y": 810,
      "deskType": "sp-desk-straight",
      "w": 84,
      "h": 84
    },
    {
      "id": "d15",
      "dept": "Operations",
      "x": 1110,
      "y": 810,
      "deskType": "sp-desk-straight",
      "w": 84,
      "h": 84
    }
  ];
  var PROPS = [
    {
      "id": "p-bk-1",
      "type": "sp-credenza-low",
      "x": 100,
      "y": 140,
      "w": 56,
      "h": 38,
      "label": "Executive Library"
    },
    {
      "id": "p-pl-1",
      "type": "sp-plant-palm",
      "x": 480,
      "y": 140,
      "w": 46,
      "h": 56,
      "label": "Fiddle Leaf Fig"
    },
    {
      "id": "p-tb-1",
      "type": "sp-desk-corner-l",
      "x": 140,
      "y": 280,
      "w": 56,
      "h": 42,
      "label": "Private Discussion Table"
    },
    {
      "id": "p-ch-1",
      "type": "sp-chair-task",
      "x": 160,
      "y": 208,
      "w": 36,
      "h": 56,
      "label": "Guest Chair"
    },
    {
      "id": "p-srv-1",
      "type": "sp-credenza-low",
      "x": 1194,
      "y": 130,
      "w": 56,
      "h": 38,
      "label": "AI Compute Rack A"
    },
    {
      "id": "p-srv-2",
      "type": "sp-credenza-low",
      "x": 1122,
      "y": 130,
      "w": 56,
      "h": 38,
      "label": "AI Compute Rack B"
    },
    {
      "id": "p-wb-1",
      "type": "sp-artwork-abstract",
      "x": 620,
      "y": 136,
      "w": 48,
      "h": 56,
      "label": "Architecture Board"
    },
    {
      "id": "p-bt-1",
      "type": "sp-desk-straight",
      "x": 680,
      "y": 680,
      "w": 56,
      "h": 40,
      "label": "Main Conference Table"
    },
    {
      "id": "p-bc-1",
      "type": "sp-chair-task",
      "x": 700,
      "y": 608,
      "w": 36,
      "h": 56,
      "label": "Board Chair"
    },
    {
      "id": "p-bc-2",
      "type": "sp-chair-task",
      "x": 750,
      "y": 640,
      "w": 36,
      "h": 56,
      "label": "Board Chair"
    },
    {
      "id": "p-wb-2",
      "type": "sp-artwork-abstract",
      "x": 100,
      "y": 536,
      "w": 48,
      "h": 56,
      "label": "Design Moodboard"
    },
    {
      "id": "p-cch-1",
      "type": "sp-counter-reception-curved",
      "x": 100,
      "y": 760,
      "w": 56,
      "h": 40,
      "label": "Studio Lounge Sofa"
    },
    {
      "id": "p-ct-1",
      "type": "sp-pedestal-mobile",
      "x": 180,
      "y": 780,
      "w": 42,
      "h": 56,
      "label": "Design Sketch Table"
    },
    {
      "id": "p-fl-1",
      "type": "sp-cabinet-filing-tall",
      "x": 960,
      "y": 576,
      "w": 32,
      "h": 56,
      "label": "Filing Storage"
    },
    {
      "id": "p-wb-3",
      "type": "sp-artwork-abstract",
      "x": 1060,
      "y": 576,
      "w": 48,
      "h": 56,
      "label": "Operations Kanban"
    },
    {
      "id": "p-fr-1",
      "type": "sp-refrigerator-compact",
      "x": 1330,
      "y": 140,
      "w": 40,
      "h": 56,
      "label": "Kitchen Fridge"
    },
    {
      "id": "p-cf-1",
      "type": "sp-mug",
      "x": 1380,
      "y": 156,
      "w": 56,
      "h": 56,
      "label": "Espresso Bar"
    },
    {
      "id": "p-cl-1",
      "type": "sp-water-bottle",
      "x": 1446,
      "y": 140,
      "w": 30,
      "h": 56,
      "label": "Water Dispenser"
    },
    {
      "id": "p-arc-1",
      "type": "sp-control-panel",
      "x": 1580,
      "y": 140,
      "w": 48,
      "h": 56,
      "label": "Retro Arcade: Pixel Fighter"
    },
    {
      "id": "p-cch-2",
      "type": "sp-counter-reception-curved",
      "x": 1460,
      "y": 440,
      "w": 56,
      "h": 40,
      "label": "Breakroom Sofa"
    },
    {
      "id": "p-pl-2",
      "type": "sp-plant-broadleaf",
      "x": 1600,
      "y": 440,
      "w": 46,
      "h": 56,
      "label": "Indoor Palm"
    }
  ];
  var SPRITES = [
    {
      "id": "sp-artwork-abstract",
      "l": "Artwork Abstract",
      "c": "Decor",
      "w": 24,
      "h": 28
    },
    {
      "id": "sp-bin-recycling",
      "l": "Bin Recycling",
      "c": "Decor",
      "w": 21,
      "h": 28
    },
    {
      "id": "sp-bin-waste",
      "l": "Bin Waste",
      "c": "Decor",
      "w": 22,
      "h": 28
    },
    {
      "id": "sp-partition-fabric",
      "l": "Partition Fabric",
      "c": "Decor",
      "w": 24,
      "h": 28
    },
    {
      "id": "sp-plant-broadleaf",
      "l": "Plant Broadleaf",
      "c": "Decor",
      "w": 23,
      "h": 28
    },
    {
      "id": "sp-plant-palm",
      "l": "Plant Palm",
      "c": "Decor",
      "w": 23,
      "h": 28
    },
    {
      "id": "sp-plant-snake",
      "l": "Plant Snake",
      "c": "Decor",
      "w": 18,
      "h": 28
    },
    {
      "id": "sp-refrigerator-compact",
      "l": "Refrigerator Compact",
      "c": "Decor",
      "w": 20,
      "h": 28
    },
    {
      "id": "sp-stand-umbrella",
      "l": "Stand Umbrella",
      "c": "Decor",
      "w": 16,
      "h": 28
    },
    {
      "id": "sp-tree-indoor",
      "l": "Tree Indoor",
      "c": "Decor",
      "w": 22,
      "h": 28
    },
    {
      "id": "sp-camera-security",
      "l": "Camera Security",
      "c": "Electronics",
      "w": 28,
      "h": 24
    },
    {
      "id": "sp-clock-wall",
      "l": "Clock Wall",
      "c": "Electronics",
      "w": 27,
      "h": 28
    },
    {
      "id": "sp-computer-tower",
      "l": "Computer Tower",
      "c": "Electronics",
      "w": 19,
      "h": 28
    },
    {
      "id": "sp-control-panel",
      "l": "Control Panel",
      "c": "Electronics",
      "w": 24,
      "h": 28
    },
    {
      "id": "sp-copier-multifunction",
      "l": "Copier Multifunction",
      "c": "Electronics",
      "w": 21,
      "h": 28
    },
    {
      "id": "sp-lamp-desk",
      "l": "Lamp Desk",
      "c": "Electronics",
      "w": 22,
      "h": 28
    },
    {
      "id": "sp-lamp-floor",
      "l": "Lamp Floor",
      "c": "Electronics",
      "w": 11,
      "h": 28
    },
    {
      "id": "sp-laptop-closed",
      "l": "Laptop Closed",
      "c": "Electronics",
      "w": 28,
      "h": 18
    },
    {
      "id": "sp-laptop-open-off",
      "l": "Laptop Open Off",
      "c": "Electronics",
      "w": 28,
      "h": 27
    },
    {
      "id": "sp-monitor-single-off",
      "l": "Monitor Single Off",
      "c": "Electronics",
      "w": 27,
      "h": 28
    },
    {
      "id": "sp-printer-small",
      "l": "Printer Small",
      "c": "Electronics",
      "w": 28,
      "h": 25
    },
    {
      "id": "sp-projector",
      "l": "Projector",
      "c": "Electronics",
      "w": 28,
      "h": 23
    },
    {
      "id": "sp-shredder",
      "l": "Shredder",
      "c": "Electronics",
      "w": 25,
      "h": 28
    },
    {
      "id": "sp-ups",
      "l": "Ups",
      "c": "Electronics",
      "w": 23,
      "h": 28
    },
    {
      "id": "sp-cabinet-filing-tall",
      "l": "Cabinet Filing Tall",
      "c": "Furniture",
      "w": 16,
      "h": 28
    },
    {
      "id": "sp-chair-meeting",
      "l": "Chair Meeting",
      "c": "Furniture",
      "w": 21,
      "h": 28
    },
    {
      "id": "sp-chair-task",
      "l": "Chair Task",
      "c": "Furniture",
      "w": 18,
      "h": 28
    },
    {
      "id": "sp-chair-visitor",
      "l": "Chair Visitor",
      "c": "Furniture",
      "w": 21,
      "h": 28
    },
    {
      "id": "sp-counter-reception-curved",
      "l": "Counter Reception Curved",
      "c": "Furniture",
      "w": 28,
      "h": 20
    },
    {
      "id": "sp-credenza-low",
      "l": "Credenza Low",
      "c": "Furniture",
      "w": 28,
      "h": 19
    },
    {
      "id": "sp-desk-corner-l",
      "l": "Desk Corner L",
      "c": "Furniture",
      "w": 28,
      "h": 21
    },
    {
      "id": "sp-desk-modesty-panel",
      "l": "Desk Modesty Panel",
      "c": "Furniture",
      "w": 28,
      "h": 21
    },
    {
      "id": "sp-desk-standing",
      "l": "Desk Standing",
      "c": "Furniture",
      "w": 28,
      "h": 23
    },
    {
      "id": "sp-desk-straight",
      "l": "Desk Straight",
      "c": "Furniture",
      "w": 28,
      "h": 20
    },
    {
      "id": "sp-pedestal-mobile",
      "l": "Pedestal Mobile",
      "c": "Furniture",
      "w": 21,
      "h": 28
    },
    {
      "id": "sp-stool-high",
      "l": "Stool High",
      "c": "Furniture",
      "w": 18,
      "h": 28
    },
    {
      "id": "sp-archive-box",
      "l": "Archive Box",
      "c": "Props",
      "w": 28,
      "h": 27
    },
    {
      "id": "sp-calculator",
      "l": "Calculator",
      "c": "Props",
      "w": 28,
      "h": 27
    },
    {
      "id": "sp-clipboard-blank",
      "l": "Clipboard Blank",
      "c": "Props",
      "w": 27,
      "h": 28
    },
    {
      "id": "sp-folder-closed",
      "l": "Folder Closed",
      "c": "Props",
      "w": 28,
      "h": 25
    },
    {
      "id": "sp-frame-photo-blank",
      "l": "Frame Photo Blank",
      "c": "Props",
      "w": 24,
      "h": 28
    },
    {
      "id": "sp-headphones",
      "l": "Headphones",
      "c": "Props",
      "w": 27,
      "h": 28
    },
    {
      "id": "sp-keys-set",
      "l": "Keys Set",
      "c": "Props",
      "w": 24,
      "h": 28
    },
    {
      "id": "sp-mug",
      "l": "Mug",
      "c": "Props",
      "w": 28,
      "h": 28
    },
    {
      "id": "sp-notebook-closed",
      "l": "Notebook Closed",
      "c": "Props",
      "w": 28,
      "h": 25
    },
    {
      "id": "sp-organizer-desk",
      "l": "Organizer Desk",
      "c": "Props",
      "w": 28,
      "h": 25
    },
    {
      "id": "sp-papers-stack",
      "l": "Papers Stack",
      "c": "Props",
      "w": 28,
      "h": 25
    },
    {
      "id": "sp-pen-cup",
      "l": "Pen Cup",
      "c": "Props",
      "w": 19,
      "h": 28
    },
    {
      "id": "sp-stapler",
      "l": "Stapler",
      "c": "Props",
      "w": 28,
      "h": 25
    },
    {
      "id": "sp-succulent-small",
      "l": "Succulent Small",
      "c": "Props",
      "w": 21,
      "h": 28
    },
    {
      "id": "sp-tape-dispenser",
      "l": "Tape Dispenser",
      "c": "Props",
      "w": 28,
      "h": 28
    },
    {
      "id": "sp-usb-drive",
      "l": "Usb Drive",
      "c": "Props",
      "w": 28,
      "h": 25
    },
    {
      "id": "sp-wastebasket-small",
      "l": "Wastebasket Small",
      "c": "Props",
      "w": 24,
      "h": 28
    },
    {
      "id": "sp-water-bottle",
      "l": "Water Bottle",
      "c": "Props",
      "w": 15,
      "h": 28
    }
  ];
  var SPRITE_BY_ID = new Map(SPRITES.map((sprite2) => [sprite2.id, sprite2]));
  var sprite = (id) => SPRITE_BY_ID.get(id);
  function defaultPlan() {
    return {
      rooms: ROOMS.map((room) => ({ ...room })),
      desks: DESKS.map((desk) => ({ ...desk })),
      props: PROPS.map((prop) => ({ ...prop }))
    };
  }

  // apps/web/src/world/camera.ts
  var FIT_MIN_SCALE = 0.1;
  var MIN_SCALE = 0.1;
  var MAX_SCALE = 3;
  var LADDER = [0.5, 1, 2, 3];
  var EASE = 0.18;
  var clampScale = (scale) => Number.isFinite(scale) ? Math.min(MAX_SCALE, Math.max(MIN_SCALE, scale)) : 1;
  var clampFitScale = (scale) => Number.isFinite(scale) ? Math.min(MAX_SCALE, Math.max(FIT_MIN_SCALE, scale)) : 1;
  function fitCamera(width, height, margin = 24) {
    const usable = Math.max(1, width - margin * 2);
    const usableH = Math.max(1, height - margin * 2);
    const scale = clampFitScale(Math.min(usable / WORLD.w, usableH / WORLD.h));
    return {
      scale,
      x: (width - WORLD.w * scale) / 2,
      y: (height - WORLD.h * scale) / 2
    };
  }
  function toPlan(camera, screenX, screenY) {
    return { x: (screenX - camera.x) / camera.scale, y: (screenY - camera.y) / camera.scale };
  }
  function toScreen(camera, planX, planY) {
    return { x: planX * camera.scale + camera.x, y: planY * camera.scale + camera.y };
  }
  function zoomAbout(camera, scale, screenX, screenY) {
    const next = clampScale(scale);
    const plan = toPlan(camera, screenX, screenY);
    return { scale: next, x: screenX - plan.x * next, y: screenY - plan.y * next };
  }
  var zoomBy = (camera, factor, screenX, screenY) => zoomAbout(camera, camera.scale * factor, screenX, screenY);
  var zoomByCentre = (camera, factor, width, height) => zoomAbout(camera, camera.scale * factor, width / 2, height / 2);
  function clampAxis(view, content, position, slack) {
    if (content + slack * 2 <= view) return (view - content) / 2;
    return Math.min(slack, Math.max(view - content - slack, position));
  }
  function clampCamera(camera, width, height, slack = 4e3) {
    const w = WORLD.w * camera.scale;
    const h = WORLD.h * camera.scale;
    return {
      scale: camera.scale,
      x: clampAxis(width, w, camera.x, slack),
      y: clampAxis(height, h, camera.y, slack)
    };
  }
  function clampCameraForZoom(camera, width, height) {
    const slack = Math.min(240, Math.max(80, width / 3));
    return clampCamera(camera, width, height, slack);
  }
  var panBy = (camera, dx, dy) => ({
    scale: camera.scale,
    x: camera.x + dx,
    y: camera.y + dy
  });
  function centreOn(camera, planX, planY, width, height) {
    return { scale: camera.scale, x: width / 2 - planX * camera.scale, y: height / 2 - planY * camera.scale };
  }
  function nextRung(scale, direction) {
    if (direction === 1) return LADDER.find((rung) => rung > scale + 1e-6) ?? MAX_SCALE;
    return [...LADDER].reverse().find((rung) => rung < scale - 1e-6) ?? MIN_SCALE;
  }
  function ease(from, to, amount = EASE) {
    const scale = from.scale + (to.scale - from.scale) * amount;
    const x = from.x + (to.x - from.x) * amount;
    const y = from.y + (to.y - from.y) * amount;
    const near = Math.abs(to.scale - scale) < 1e-3 && Math.abs(to.x - x) < 0.2 && Math.abs(to.y - y) < 0.2;
    return near ? to : { scale, x, y };
  }
  var cameraTransform = (camera) => `translate3d(${camera.x}px, ${camera.y}px, 0) scale(${camera.scale})`;
  function wheelFactor(deltaY, deltaMode, ctrlKey = false) {
    const perLine = 16;
    const perPage = 400;
    const pixels = deltaMode === 1 ? deltaY * perLine : deltaMode === 2 ? deltaY * perPage : deltaY;
    const capped = Math.max(-240, Math.min(240, pixels));
    const rate = ctrlKey ? 4e-3 : 16e-4;
    return Math.exp(-capped * rate);
  }

  // apps/web/src/world/prop-paths.ts
  function shapeFor(type) {
    const id = type.replace(/^sp-/, "");
    if (id.startsWith("desk")) return "desk";
    if (id.startsWith("chair") || id.startsWith("stool")) return "chair";
    if (id.startsWith("plant") || id.startsWith("tree") || id.startsWith("succulent")) return "plant";
    if (id.startsWith("cabinet") || id.startsWith("credenza") || id.startsWith("pedestal") || id.startsWith("organizer")) return "cabinet";
    if (id.startsWith("laptop") || id.startsWith("monitor") || id.startsWith("computer") || id.startsWith("camera") || id.startsWith("copier") || id.startsWith("printer") || id.startsWith("projector")) return "screen";
    if (id.startsWith("counter") || id.startsWith("lamp") || id.startsWith("control")) return "sofa";
    if (id.startsWith("artwork") || id.startsWith("frame") || id.startsWith("clock") || id.startsWith("partition")) return "board";
    if (id.startsWith("refrigerator") || id.startsWith("water") || id.startsWith("shredder") || id.startsWith("ups") || id.startsWith("bin")) return "fridge";
    if (id.startsWith("mug") || id.startsWith("keys") || id.startsWith("stapler") || id.startsWith("pen") || id.startsWith("papers") || id.startsWith("notebook") || id.startsWith("tape") || id.startsWith("usb") || id.startsWith("clipboard") || id.startsWith("folder") || id.startsWith("archive") || id.startsWith("calculator") || id.startsWith("headphones") || id.startsWith("wastebasket") || id.startsWith("stand")) return "box";
    if (id.startsWith("table")) return "table";
    return "box";
  }
  var PROP_PATHS = {
    // a top slab with two legs
    desk: "M2 10h24v3H2zM4 13h3v11H4zM21 13h3v11h-3z",
    chair: "M9 5h10v3H9zM10 8h8v8h-8zM9 16h2v8H9zM17 16h2v8h-2z",
    table: "M3 9h22v4H3zM6 13h3v10H6zM19 13h3v10h-3z",
    plant: "M12 17h4v8h-4zM8 6h4v11H8zM16 4h4v13h-4zM9 9h10v8H9z",
    cabinet: "M5 4h18v21H5zM6 6h16v8H6zM6 17h16v6H6z",
    screen: "M4 6h20v13H4zM11 19h6v4h-6zM6 8h16v9H6z",
    sofa: "M3 12h22v7H3zM5 8h4v4H5zM19 8h4v4h-4zM4 19h3v3H4zM21 19h3v3h-3z",
    arcade: "M6 3h16v22H6zM9 6h10v8H9zM10 17h3v3h-3zM16 17h3v3h-3z",
    board: "M3 4h22v16H3zM6 7h16v10H6zM10 21h8v3h-8z",
    fridge: "M7 3h14v22H7zM8 5h12v8H8zM8 14h12v10H8zM12 17h4v2h-4z",
    box: "M5 8h18v16H5zM8 4h12v4H8zM12 14h4v4h-4z"
  };
  var PROP_GRID = 28;

  // apps/web/src/world/plan.ts
  var DEFAULT_LAYOUT = defaultPlan();
  var roomAt = (plan, x, y) => plan.rooms.find((room) => x >= room.x && x <= room.x + room.w && y >= room.y && y <= room.y + room.h);
  var desksOf = (dept) => DESKS.filter((desk) => desk.dept === dept).sort((a, b) => a.y - b.y || a.x - b.x);
  var snap = (value) => Math.round(value / WORLD.snap) * WORLD.snap;

  // apps/web/src/world/seat.ts
  function seatAgents(plan, agents, tasks) {
    const byDesk = new Map(plan.desks.map((desk) => [desk.id, null]));
    const free = [...agents];
    const take = (desk, match) => {
      if (byDesk.get(desk.id)) return;
      const found = free.find((agent) => match(agent, desk));
      if (!found) return;
      byDesk.set(desk.id, found);
      free.splice(free.indexOf(found), 1);
    };
    const themed = (agent, desk) => {
      const dept = (agent.department ?? "").toLowerCase();
      const room = desk.dept.toLowerCase();
      if (dept.includes("lead") || dept.includes("exec")) return room === "executive";
      if (dept.includes("engineer") || dept.includes("model")) return room === "engineering";
      if (dept.includes("design") || dept.includes("product")) return room === "design";
      if (dept.includes("operat") || dept.includes("growth")) return room === "operations";
      return false;
    };
    for (const desk of plan.desks) take(desk, (agent, at) => (agent.department ?? "") === at.dept);
    for (const desk of plan.desks) take(desk, themed);
    for (const desk of plan.desks) take(desk, () => true);
    return plan.desks.map((desk) => {
      const agent = byDesk.get(desk.id) ?? null;
      const mine = agent ? tasks.filter((task) => task.ownerAgentId === agent.id) : [];
      return { desk, agent, tasks: mine, working: mine.some((task) => task.stage === "progress") };
    });
  }

  // apps/web/src/world/gestures.ts
  var GLIDE_FRICTION = 0.92;
  var GLIDE_STOP = 0.05;
  function glideStep(velocity) {
    const next = velocity * GLIDE_FRICTION;
    return Math.abs(next) < GLIDE_STOP ? 0 : next;
  }
  function glideDistance(velocity) {
    let v = velocity;
    let total = 0;
    for (let i = 0; i < 600 && v !== 0; i += 1) {
      total += v;
      v = glideStep(v);
    }
    return total;
  }
  var distanceBetween = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
  var midpoint = (a, b) => ({
    x: (a.x + b.x) / 2,
    y: (a.y + b.y) / 2
  });
  function pinchCamera(start, distance, mid) {
    if (start.distance <= 0) return start.camera;
    const zoomed = zoomBy(start.camera, distance / start.distance, start.mid.x, start.mid.y);
    return { ...zoomed, x: zoomed.x + (mid.x - start.mid.x), y: zoomed.y + (mid.y - start.mid.y) };
  }
  var DOUBLE_CLICK_FACTOR = 1.6;
  function doubleClickZoom(camera, px, py, invert = false) {
    return zoomBy(camera, invert ? 1 / DOUBLE_CLICK_FACTOR : DOUBLE_CLICK_FACTOR, px, py);
  }
  return __toCommonJS(demo_entry_exports);
})();
