-- Migration 0001 — the designer's own columns: display refs, bilingual text, risk and cost.
--
-- Drizzle generated the additive parts; the two NOT NULL columns were generated as a plain
-- ALTER, which cannot work on a table that already has rows ("column contains null values").
-- This migration therefore adds them nullable, fills them with a real value, and only then
-- makes them required — the shape every future NOT NULL column should follow.
--
-- The backfill numbers a company's rows in the order they were created, which is stable for
-- existing data. New rows get their ref from the application's seed/insert path.

-- The display refs are generated by the database, from a sequence per record kind.
-- Starting points are above the designer's own numbers (TSK-142…170, DEC-31…34) so those stay
-- recognisable in the seeded company and a new record can never collide with one of them.
CREATE SEQUENCE IF NOT EXISTS "tasks_short_ref_seq" START WITH 200;--> statement-breakpoint
CREATE SEQUENCE IF NOT EXISTS "decisions_short_ref_seq" START WITH 40;--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN "name_ar" varchar(120);--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN "role_ar" varchar(80);--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN "department" varchar(80);--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN "focus" varchar(200);--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN "focus_ar" varchar(200);--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN "avatar" integer;--> statement-breakpoint
ALTER TABLE "decisions" ADD COLUMN "title_ar" varchar(200);--> statement-breakpoint
ALTER TABLE "decisions" ADD COLUMN "risk" varchar(8) DEFAULT 'low' NOT NULL;--> statement-breakpoint
ALTER TABLE "decisions" ADD COLUMN "cost_cents" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "title_ar" varchar(200);--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "description_ar" text;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "short_ref" varchar(16);--> statement-breakpoint
UPDATE "tasks" SET "short_ref" = numbered.ref
  FROM (
    SELECT "id",
           'TSK-' || lpad((row_number() OVER (PARTITION BY "company_id" ORDER BY "created_at", "id"))::text, 3, '0') AS ref
    FROM "tasks"
  ) AS numbered
  WHERE "tasks"."id" = numbered."id" AND "tasks"."short_ref" IS NULL;--> statement-breakpoint
ALTER TABLE "tasks" ALTER COLUMN "short_ref" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "tasks" ALTER COLUMN "short_ref" SET DEFAULT ('TSK-' || lpad(nextval('tasks_short_ref_seq')::text, 3, '0'));--> statement-breakpoint
ALTER TABLE "decisions" ADD COLUMN "short_ref" varchar(16);--> statement-breakpoint
UPDATE "decisions" SET "short_ref" = numbered.ref
  FROM (
    SELECT "id",
           'DEC-' || lpad((row_number() OVER (PARTITION BY "company_id" ORDER BY "created_at", "id"))::text, 2, '0') AS ref
    FROM "decisions"
  ) AS numbered
  WHERE "decisions"."id" = numbered."id" AND "decisions"."short_ref" IS NULL;--> statement-breakpoint
ALTER TABLE "decisions" ALTER COLUMN "short_ref" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "decisions" ALTER COLUMN "short_ref" SET DEFAULT ('DEC-' || lpad(nextval('decisions_short_ref_seq')::text, 2, '0'));--> statement-breakpoint
ALTER TABLE "decisions" ADD CONSTRAINT "decisions_company_ref_uq" UNIQUE("company_id","short_ref");--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_company_ref_uq" UNIQUE("company_id","short_ref");
