/**
 * The company's tables.
 *
 * Column shapes follow the verified donor `paperclipai/paperclip` (MIT,
 * `packages/db/src/schema/agents.ts`) for agents — including the budget pair in integer cents
 * and the self-referencing `reports_to` — extended with this product's runs, ledger and
 * decisions. Migrations are generated by drizzle-kit (`npm run db:generate`), never hand-written.
 *
 * Every table carries `company_id`: a second company must never be able to read the first.
 */
import { relations, sql } from 'drizzle-orm';
import {
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';
import type { AnyPgColumn } from 'drizzle-orm/pg-core';

const id = () => uuid('id').primaryKey().defaultRandom();
const companyRef = () => uuid('company_id').notNull();
const at = (name: string) => timestamp(name, { withTimezone: true, mode: 'string' });

export const companies = pgTable('companies', {
  id: id(),
  name: varchar('name', { length: 120 }).notNull(),
  createdAt: at('created_at').notNull().defaultNow(),
});

export const members = pgTable(
  'members',
  {
    id: id(),
    companyId: companyRef().references(() => companies.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 120 }).notNull(),
    email: varchar('email', { length: 200 }),
    role: varchar('role', { length: 16 }).notNull().default('member'), // owner|admin|member|viewer
    createdAt: at('created_at').notNull().defaultNow(),
  },
  (t) => ({ companyIdx: index('members_company_idx').on(t.companyId) }),
);

export const agents = pgTable(
  'agents',
  {
    id: id(),
    companyId: companyRef().references(() => companies.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 120 }).notNull(),
    role: varchar('role', { length: 80 }).notNull().default('general'),
    title: varchar('title', { length: 120 }),
    status: varchar('status', { length: 16 }).notNull().default('idle'), // idle|working|waiting|paused|error
    reportsTo: uuid('reports_to').references((): AnyPgColumn => agents.id, { onDelete: 'set null' }),
    capabilities: jsonb('capabilities').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    budgetMonthlyCents: integer('budget_monthly_cents').notNull().default(0),
    spentMonthlyCents: integer('spent_monthly_cents').notNull().default(0),
    pauseReason: text('pause_reason'),
    errorReason: text('error_reason'),
    lastHeartbeatAt: at('last_heartbeat_at'),
    createdAt: at('created_at').notNull().defaultNow(),
    updatedAt: at('updated_at').notNull().defaultNow(),
  },
  (t) => ({
    companyUq: unique('agents_company_id_uq').on(t.companyId, t.id),
    companyStatusIdx: index('agents_company_status_idx').on(t.companyId, t.status),
    companyReportsToIdx: index('agents_company_reports_to_idx').on(t.companyId, t.reportsTo),
  }),
);

export const models = pgTable(
  'models',
  {
    id: id(),
    providerModel: varchar('provider_model', { length: 80 }).notNull(),
    provider: varchar('provider', { length: 24 }).notNull(), // openai|anthropic|open
    lane: varchar('lane', { length: 12 }).notNull(), // strong|balanced|cheap
    displayName: varchar('display_name', { length: 80 }).notNull(),
    inputCentsPerMTok: integer('input_cents_per_mtok').notNull(),
    outputCentsPerMTok: integer('output_cents_per_mtok').notNull(),
    contextWindow: integer('context_window').notNull(),
    maxOutputTokens: integer('max_output_tokens').notNull(),
    lifecycle: varchar('lifecycle', { length: 16 }).notNull().default('ga'),
    lifecycleChangedAt: at('lifecycle_changed_at'),
    supports: jsonb('supports').$type<Record<string, boolean>>().notNull().default(sql`'{}'::jsonb`),
    retired: boolean('retired').notNull().default(false),
  },
  (t) => ({ providerModelUq: unique('models_provider_model_uq').on(t.provider, t.providerModel) }),
);

export const agentModels = pgTable(
  'agent_models',
  {
    agentId: uuid('agent_id').primaryKey().references(() => agents.id, { onDelete: 'cascade' }),
    modelId: uuid('model_id').notNull().references(() => models.id),
    fallbackModelIds: jsonb('fallback_model_ids').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    temperature: integer('temperature_milli').notNull().default(200), // 0.200 stored as integer
    maxOutputTokens: integer('max_output_tokens'),
  },
);

export const goals = pgTable(
  'goals',
  {
    id: id(),
    companyId: companyRef().references(() => companies.id, { onDelete: 'cascade' }),
    title: varchar('title', { length: 200 }).notNull(),
    ownerAgentId: uuid('owner_agent_id').references(() => agents.id, { onDelete: 'set null' }),
    targetDate: timestamp('target_date', { withTimezone: true, mode: 'string' }),
    status: varchar('status', { length: 16 }).notNull().default('active'),
    createdAt: at('created_at').notNull().defaultNow(),
  },
  (t) => ({ companyIdx: index('goals_company_idx').on(t.companyId) }),
);

export const edges = pgTable(
  'edges',
  {
    id: id(),
    companyId: companyRef().references(() => companies.id, { onDelete: 'cascade' }),
    fromAgentId: uuid('from_agent_id').notNull().references(() => agents.id, { onDelete: 'cascade' }),
    toAgentId: uuid('to_agent_id').notNull().references(() => agents.id, { onDelete: 'cascade' }),
    kind: varchar('kind', { length: 24 }).notNull(), // reports_to|collaborates_with|delegates_to|reviews
  },
  (t) => ({
    edgeUq: unique('edges_unique').on(t.companyId, t.fromAgentId, t.toAgentId, t.kind),
    companyIdx: index('edges_company_idx').on(t.companyId),
  }),
);

export const tasks = pgTable(
  'tasks',
  {
    id: id(),
    companyId: companyRef().references(() => companies.id, { onDelete: 'cascade' }),
    goalId: uuid('goal_id').references(() => goals.id, { onDelete: 'set null' }),
    title: varchar('title', { length: 200 }).notNull(),
    ownerAgentId: uuid('owner_agent_id').notNull().references(() => agents.id),
    stage: varchar('stage', { length: 12 }).notNull().default('backlog'), // backlog|progress|review|done
    priority: varchar('priority', { length: 12 }).notNull().default('medium'),
    progress: integer('progress').notNull().default(0),
    dueDate: timestamp('due_date', { withTimezone: true, mode: 'string' }),
    reviewRequestedByRunId: uuid('review_requested_by_run_id'),
    approvedByMemberId: uuid('approved_by_member_id').references(() => members.id, { onDelete: 'set null' }),
    createdAt: at('created_at').notNull().defaultNow(),
    updatedAt: at('updated_at').notNull().defaultNow(),
  },
  (t) => ({
    companyStageIdx: index('tasks_company_stage_idx').on(t.companyId, t.stage),
    companyOwnerIdx: index('tasks_company_owner_idx').on(t.companyId, t.ownerAgentId),
    // The contract's 0–100 bound, enforced by the database as well as the schema —
    // belt and braces: a bug in one layer must not corrupt a board column.
    progressRange: check('tasks_progress_range', sql`${t.progress} BETWEEN 0 AND 100`),
  }),
);

export const runs = pgTable(
  'runs',
  {
    id: id(),
    companyId: companyRef().references(() => companies.id, { onDelete: 'cascade' }),
    agentId: uuid('agent_id').notNull().references(() => agents.id, { onDelete: 'cascade' }),
    taskId: uuid('task_id').references(() => tasks.id, { onDelete: 'set null' }),
    modelId: uuid('model_id').notNull().references(() => models.id),
    requestedModelId: uuid('requested_model_id').notNull().references(() => models.id),
    status: varchar('status', { length: 12 }).notNull().default('running'), // running|succeeded|failed|blocked
    blockedByDecisionId: uuid('blocked_by_decision_id'),
    promptTokens: integer('prompt_tokens').notNull().default(0),
    completionTokens: integer('completion_tokens').notNull().default(0),
    costCents: integer('cost_cents').notNull().default(0),
    traceId: varchar('trace_id', { length: 120 }),
    error: text('error'),
    startedAt: at('started_at').notNull().defaultNow(),
    endedAt: at('ended_at'),
  },
  (t) => ({
    companyStartedIdx: index('runs_company_started_idx').on(t.companyId, t.startedAt),
    agentStartedIdx: index('runs_agent_started_idx').on(t.agentId, t.startedAt),
  }),
);

export const ledger = pgTable(
  'ledger',
  {
    id: id(),
    companyId: companyRef().references(() => companies.id, { onDelete: 'cascade' }),
    agentId: uuid('agent_id').notNull().references(() => agents.id, { onDelete: 'cascade' }),
    runId: uuid('run_id').references(() => runs.id, { onDelete: 'cascade' }),
    kind: varchar('kind', { length: 16 }).notNull().default('model_call'),
    modelId: uuid('model_id').references(() => models.id),
    promptTokens: integer('prompt_tokens').notNull().default(0),
    completionTokens: integer('completion_tokens').notNull().default(0),
    amountCents: integer('amount_cents').notNull(),
    at: at('at').notNull().defaultNow(),
  },
  (t) => ({
    companyAtIdx: index('ledger_company_at_idx').on(t.companyId, t.at),
    agentAtIdx: index('ledger_agent_at_idx').on(t.agentId, t.at),
  }),
);

export const decisions = pgTable(
  'decisions',
  {
    id: id(),
    companyId: companyRef().references(() => companies.id, { onDelete: 'cascade' }),
    kind: varchar('kind', { length: 24 }).notNull(),
    status: varchar('status', { length: 16 }).notNull().default('pending'),
    taskId: uuid('task_id').references(() => tasks.id, { onDelete: 'set null' }),
    runId: uuid('run_id').references(() => runs.id, { onDelete: 'set null' }),
    agentId: uuid('agent_id').references(() => agents.id, { onDelete: 'set null' }),
    title: varchar('title', { length: 200 }).notNull(),
    rule: jsonb('rule').$type<Record<string, unknown>>().notNull(),
    diff: jsonb('diff').$type<Record<string, unknown>>().notNull(),
    audit: jsonb('audit').$type<Record<string, unknown>>().notNull(),
    outcome: text('outcome'),
    outcomeAt: at('outcome_at'),
    createdAt: at('created_at').notNull().defaultNow(),
  },
  (t) => ({
    companyStatusIdx: index('decisions_company_status_idx').on(t.companyId, t.status),
    // One open decision per run at a time; the donor's idempotency lesson, enforced by the database.
    uniqueOpenPerRun: unique('decisions_open_per_run_uq').on(t.runId, t.status),
  }),
);

export const threads = pgTable(
  'threads',
  {
    id: id(),
    companyId: companyRef().references(() => companies.id, { onDelete: 'cascade' }),
    title: varchar('title', { length: 200 }).notNull(),
    participantAgentIds: jsonb('participant_agent_ids').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    participantMemberIds: jsonb('participant_member_ids').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    internal: boolean('internal').notNull().default(false),
    lastMessageAt: at('last_message_at'),
    createdAt: at('created_at').notNull().defaultNow(),
  },
  (t) => ({ companyIdx: index('threads_company_idx').on(t.companyId, t.internal) }),
);

export const messages = pgTable(
  'messages',
  {
    id: id(),
    threadId: uuid('thread_id').notNull().references(() => threads.id, { onDelete: 'cascade' }),
    companyId: companyRef().references(() => companies.id, { onDelete: 'cascade' }),
    authorKind: varchar('author_kind', { length: 8 }).notNull(), // agent|member|system
    authorId: varchar('author_id', { length: 40 }).notNull(),
    parts: jsonb('parts').$type<unknown[]>().notNull().default(sql`'[]'::jsonb`),
    runId: uuid('run_id').references(() => runs.id, { onDelete: 'set null' }),
    modelId: uuid('model_id').references(() => models.id, { onDelete: 'set null' }),
    createdAt: at('created_at').notNull().defaultNow(),
  },
  (t) => ({ threadIdx: index('messages_thread_idx').on(t.threadId, t.createdAt) }),
);

/* Relations — used by the API's joins and documented for the next developer. */
export const companyRelations = relations(companies, ({ many }) => ({
  agents: many(agents),
  members: many(members),
  tasks: many(tasks),
  decisions: many(decisions),
}));
export const agentRelations = relations(agents, ({ one, many }) => ({
  company: one(companies, { fields: [agents.companyId], references: [companies.id] }),
  manager: one(agents, { fields: [agents.reportsTo], references: [agents.id], relationName: 'reportsTo' }),
  model: one(agentModels, { fields: [agents.id], references: [agentModels.agentId] }),
  runs: many(runs),
}));
export const taskRelations = relations(tasks, ({ one }) => ({
  company: one(companies, { fields: [tasks.companyId], references: [companies.id] }),
  owner: one(agents, { fields: [tasks.ownerAgentId], references: [agents.id] }),
  goal: one(goals, { fields: [tasks.goalId], references: [goals.id] }),
}));
export const runRelations = relations(runs, ({ one, many }) => ({
  agent: one(agents, { fields: [runs.agentId], references: [agents.id] }),
  model: one(models, { fields: [runs.modelId], references: [models.id] }),
  ledger: many(ledger),
}));
