/** The API client. One place that knows the product's endpoints and its error shape. */
export interface ApiError {
  code: string;
  message: string;
  fields?: string[];
}

/**
 * Who is acting, fetched once and remembered.
 *
 * The interface must never invent this: ids are opaque uuids, and the literal string 'owner' used
 * to be sent from here — the API rejected it, and the board then reported the rejection as a
 * refusal by the rule. The server publishes the acting member at /api/session; this caches it.
 */
let actingMember: Promise<string> | null = null;
function actingMemberId(): Promise<string> {
  actingMember ??= request<{ member: { id: string } | null }>('/api/session').then(({ member }) => {
    if (!member) throw new Error('This company has no members yet.');
    return member.id;
  });
  return actingMember;
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, {
    headers: { 'content-type': 'application/json' },
    ...init,
  });
  if (!response.ok) {
    let error: ApiError = { code: 'network', message: 'The request could not be completed.' };
    try {
      const body = (await response.json()) as { error?: ApiError };
      if (body.error) error = body.error;
    } catch {
      /* keep the generic message */
    }
    throw Object.assign(new Error(error.message), { apiError: error, status: response.status });
  }
  return (await response.json()) as T;
}

/** One offered move, exactly as the server described it. */
export interface TransitionOffer {
  to: 'backlog' | 'progress' | 'review' | 'done';
  ok: boolean;
  reason: { en: string; ar: string } | null;
}

export interface TaskRow {
  id: string;
  /** The reference a person reads (TSK-142). Generated by the database, never from the id. */
  shortRef: string;
  title: string;
  titleAr?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  stage: 'backlog' | 'progress' | 'review' | 'done';
  priority: 'low' | 'medium' | 'high' | 'critical';
  progress: number;
  dueDate: string | null;
  ownerAgentId: string;
  owner: { id: string; name: string; nameAr?: string | null; role: string; avatar?: number | null } | null;
  offers: TransitionOffer[];
  createdAt: string;
  updatedAt: string;
}

export const api = {
  health: () => request<{ ok: boolean; version: string; company: string | null }>('/api/health'),
  company: () => request<{ company: { id: string; name: string } }>('/api/company'),
  agents: () =>
    request<{
      agents: Array<{
        id: string; name: string; nameAr: string | null; role: string; roleAr: string | null;
        department: string | null; focus: string | null; focusAr: string | null;
        avatar: number | null; status: string; modelId: string | null;
        capabilities: string[];
        budget: { limitCents: number; spentCents: number; remainingCents: number; exceeded: boolean };
      }>;
    }>('/api/agents'),
  tasks: () => request<{ tasks: TaskRow[] }>('/api/tasks'),
  moveTask: async (taskId: string, to: TransitionOffer['to']) =>
    request<{ task: { id: string; stage: string } }>(`/api/tasks/${taskId}/transition`, {
      method: 'POST',
      body: JSON.stringify({ to, actor: { kind: 'member', id: await actingMemberId() } }),
    }),
  session: () => request<{ member: { id: string; name: string; role: string } | null }>('/api/session'),
  /** The demo's task form, both directions. The reference a person reads comes back from the server. */
  createTask: (input: {
    title: string; titleAr?: string | null; description?: string | null; descriptionAr?: string | null;
    ownerAgentId: string; stage: TaskRow['stage']; priority: TaskRow['priority'];
    progress?: number; dueDate?: string | null;
  }) => request<{ task: TaskRow }>('/api/tasks', { method: 'POST', body: JSON.stringify(input) }),
  updateTask: (taskId: string, patch: {
    title?: string; titleAr?: string | null; description?: string | null; descriptionAr?: string | null;
    ownerAgentId?: string; stage?: TaskRow['stage']; priority?: TaskRow['priority'];
    progress?: number; dueDate?: string | null;
  }) => request<{ task: TaskRow }>(`/api/tasks/${taskId}`, { method: 'PATCH', body: JSON.stringify(patch) }),
  decisions: (status?: string) =>
    request<{
      decisions: Array<{
        id: string; kind: string; status: string; shortRef: string; title: string; titleAr: string | null;
        risk: string; costCents: number; agentId: string | null;
        rule: { id: string; observed: number; threshold: number; unit: string };
        diff: { kind: string; summary: string; summaryAr?: string | null; before: string | null; after: string | null };
        audit: { raisedAt: string; decidedByLabel: string | null; decidedAt: string | null };
        outcome: string | null;
      }>;
    }>(`/api/decisions${status ? `?status=${status}` : ''}`),
  decide: (decisionId: string, verdict: 'approve' | 'reject') =>
    request<{ outcome: { kind: string; status?: string }; applied?: { outcome?: string } }>(
      `/api/decisions/${decisionId}/decide`,
      { method: 'POST', body: JSON.stringify({ verdict }) },
    ),
  models: () =>
    request<{ models: Array<{ id: string; displayName: string; lane: string; inputCentsPerMTok: number; outputCentsPerMTok: number; lifecycle: string }> }>(
      '/api/models',
    ),
  views: (view: string, state: string) => request<{ view: string; state: string }>(`/api/views/${view}?state=${state}`),
};
